on: 
 push: 
  branches:
    - master






jobs:
 build:
  runs-on: ubuntu-latest




  steps:
    - name: 'printing test message'
      run: pwd

      -name: 'printing name'
      run: echo "Hello, World!"